version: '3.9'
services:
  aads-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aads-dashboard
    restart: always
    ports:
      - '3100:3100'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://aads.newtalk.kr/api/v1
      - PORT=3100
    networks:
      - aads_network

networks:
  aads_network:
    external: true
